### ISSUE TITLE
Docker containers in CWL.

### ISSUE THREAD

**Issue by mberacochea** [EBI-Metagenomics/emg-viral-pipeline#10]
Review CWL docker hints and the Dockerfiles.

Missing ones:
- [x] fasta rename/restore
- [x] hmmscan_format_table
- [x] IMG VR - Blast
- [x] Krona

**Comment by hoelzer** [comment]
I think I can provide some, at least for Blast and Krona

**Comment by mberacochea** [comment]
> I think I can provide some, at least for Blast and Krona

cool, I would like to push them to the mgnify account.

**Comment by hoelzer** [comment]
yep, makes sense. let me check what I have and I will ad the Dockerfiles here so you can move everything to the mgnify acc

**Comment by hoelzer** [comment]
I added Dockerfiles I am using in the nextflow pipepline for 

- IMG VR Blast
- Krona
- Sankey

The Sankey plot is at the moment only implemented in the Nextflow pipeline and it's still a little bit hacky, but I really like the visualization so maybe you also want to use this at some point besides the Kronas (also for bacteria). So here you already have now the Dockerfile ;) 

For the fasta rename/restore script I just used a simple Docker with python3.7 installed:
https://hub.docker.com/repository/docker/mhoelzer/python3_virify
(unfortunately, I can't find the Dockerfile and it seems this is not available in Dockerhub)

**Comment by mberacochea** [comment]
This is completed for CWL, I'm testing it in the cluster.

**Comment by hoelzer** [comment]
when you updated/moved all the docker images to a more central account we can also update them in the nextflow configuration?

**Comment by mberacochea** [comment]
Yes, I'll update the containers in both implementations.

**Comment by mberacochea** [comment]
Finally done.

**Comment by hoelzer** [comment]
wouhuh! :) milestone!
