### ISSUE TITLE
 `annotate:ratio_evalue (1)` terminated with an error exit status (1) -- 'nextflow-autodownload-databases' Is a directory error

### ISSUE THREAD

**Issue by GomathiNayagam** [EBI-Metagenomics/emg-viral-pipeline#101]
I am running virify on a local computer with docker image. The pipeline stops at annotate: ratio_evalue. It seems to successfully complete hmm_post-processing step. But for the next step it seems to look for hmm tblout file in 'nextflow-autodownload-databases'. I had downloaded few of the databases manually in nextflow-autodownload-databases and had pointed the pipeline to the directory. Please help me understand this issue.

**Comment by hoelzer** [comment]
Hey @GomathiNayagam sorry that we did not respond in time. 

Do you still have this issue with the latest version of the pipeline? If so, please try to re-download the databases again with the latest version. 

Please feel free to reopen this issue if the problem persists.
