### ISSUE TITLE
Repository may be corrupted

### ISSUE THREAD

**Issue by Ales-ibt** [EBI-Metagenomics/emg-viral-pipeline#111]
Hello guys!

Thank you for updating the viral taxonomy in VIRify version 2. I installed the new version using `nextflow pull`.

`$ nextflow info EBI-Metagenomics/emg-viral-pipeline
 project name: EBI-Metagenomics/emg-viral-pipeline
 repository  : https://github.com/EBI-Metagenomics/emg-viral-pipeline
 local path  : /homes/ales/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline
 main script : virify.nf
 revisions   : 
   master (default)
   bugfix/contig-tax-assign-unkown-taxa
   dev
   docker
   ete3
   feature/cwl-mgnify-proteindb-integration
   no_bitscore_filter
   no_pprmeta
   pprmeta_score
   v0.1 [t]
   v0.2.0 [t]
   v0.2.0-no-pprmeta [t]
   v0.3.0 [t]
   v0.4.0 [t]
   v1.0 [t]
   v1.1 [t]
   v2.0.0 [t]
`

And I run the pipeline with:

`$ nextflow run EBI-Metagenomics/emg-viral-pipeline -r v2.0.0 --fasta $sample.fasta -profile ebi,singularity`

I am now testing the tool and I am having problems running the program in a large number of samples. I have 261 hybrid assemblies of bacterial isolates and every time I launch the jobs in LSF I have around 70% of the samples with the following Nextflow error:

`N E X T F L O W  ~  version 21.10.0
Unknown error accessing project 'EBI-Metagenomics/emg-viral-pipeline' -- Repository may be corrupted: /homes/ales/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline`

This is an example of the output in the .nextflow.log:

`$ cat .nextflow.log 
Aug-04 12:39:30.572 [main] DEBUG nextflow.cli.Launcher - $> nextflow run EBI-Metagenomics/emg-viral-pipeline -r v2.0.0 --fasta PB_F66.fasta -profile ebi,singularity
Aug-04 12:39:30.768 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.10.0
Aug-04 12:39:31.655 [main] DEBUG nextflow.scm.AssetManager - Git config: /homes/ales/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline/.git/config; branch: master; remote: origin; url: https://github.com/EBI-Metagenomics/emg-viral-pipeline.git
Aug-04 12:39:31.673 [main] DEBUG nextflow.scm.AssetManager - Git config: /homes/ales/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline/.git/config; branch: master; remote: origin; url: https://github.com/EBI-Metagenomics/emg-viral-pipeline.git
Aug-04 12:39:31.949 [main] DEBUG nextflow.cli.Launcher - Operation aborted
org.eclipse.jgit.api.errors.JGitInternalException: Cannot lock /homes/ales/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline/.git/index. Ensure that no other process has an open file handle on the lock file /homes/ales/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline/.git/index.lock, then you may delete the lock file and retry.
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:334)
	at nextflow.scm.AssetManager.checkout(AssetManager.groovy:927)
	at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:382)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:266)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /homes/ales/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline/.git/index. Ensure that no other process has an open file handle on the lock file /homes/ales/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline/.git/index.lock, then you may delete the lock file and retry.
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:252)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:329)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:295)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1282)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:268)
	... 5 common frames omitted
`

I am kind of 'solving' the issue by re-launching the jobs but every time I do I have around 70% of the new jobs failing because of this problem with the lock file.

Thanks in advance!

Ales.

**Comment by mberacochea** [comment]
Cool :)

**Comment by hoelzer** [comment]
Great!

(just learned about `nextflow drop`)
