### ISSUE TITLE
Input file name collision on 'annotate:write_gff'

### ISSUE THREAD

**Issue by FabioPossebon** [EBI-Metagenomics/emg-viral-pipeline#118]
Hi! I am trying to run the pipeline for 12 samples, with the following parameters:

`nextflow run EBI-Metagenomics/emg-viral-pipeline --fasta "./contigs_rnaSpades/*.fasta" --cores 8 -profile local,docker -w work --databases databases/ --length 2.0 `

It goes to every process until 'annotate:write_gff', when this error is shown:

ERROR ~ Error executing process > 'annotate:write_gff'

Caused by:
  Process `annotate:write_gff` input file name collision -- There are multiple input files for each of the following file names: low_confidence_viral_contigs_prodigal_annotation_taxonomy.tsv, low_confidence_viral_contigs_prodigal_annotation.tsv, low_confidence_viral_contigs_quality_summary.tsv, prophages_quality_summary.tsv, high_confidence_viral_contigs_quality_summary.tsv

Is there any solution for this? Thank you a lot!

**Comment by mberacochea** [comment]
Hi @FabioPossebon

he pipeline doesn't support multiple input fasta files, you will have to lunch multiples instances of the pipeline (one per assembly)

Cheers

**Comment by hoelzer** [comment]
Maybe it helps to try

```bash
nextflow run EBI-Metagenomics/emg-viral-pipeline --fasta './contigs_rnaSpades/*.fasta' --cores 8 -profile local,docker -w work --databases databases/ --length 2.0 
```

Attention, the difference is 

```bash
'./contigs_rnaSpades/*.fasta'
```

instead of

```bash
"./contigs_rnaSpades/*.fasta"
```

Then, the pipeline should run and span multiple processes for the different FASTA files.
