### ISSUE TITLE
Not able to run "nextflow pull EBI-Metagenomics/emg-viral-pipeline"

### ISSUE THREAD

**Issue by arpit20328** [EBI-Metagenomics/emg-viral-pipeline#121]
When I run    "nextflow pull EBI-Metagenomics/emg-viral-pipeline"

I get error :

Checking EBI-Metagenomics/emg-viral-pipeline ...
Project config file is malformed -- Cause: Compile failed for sources FixedSetSources[name='/groovy/script/Script43C7013E1B85D3533DD5611705899A16/_nf_config_be99724f']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/groovy/script/Script43C7013E1B85D3533DD5611705899A16/_nf_config_be99724f: 54: The LHS of an assignment should be a variable or a field accessing expression @ line 54, column 20.
       output = /home/arpit/Karishma_data_set_Wochenendr_master_15th_march_result/
                      ^

1 error

Any solution ?

**Comment by hoelzer** [comment]
Hey! 

Are you using the latest `nextflow -version`? How did you install nextflow? Can you pull other pipelines? Let's say `nextflow pull hoelzer/pocp`?

**Comment by arpit20328** [comment]
@hoelzer 

sry for late reply...

No I am not able to pull other pipelines also

**Comment by hoelzer** [comment]
I am closing this bc this seems to be a nextflow installation/configuration error not related to VIRify. Please reopen @arpit20328 if you need further assistance!
