### ISSUE TITLE
validation errors for pipeline.cwl

### ISSUE THREAD

**Issue by uludag** [EBI-Metagenomics/emg-viral-pipeline#49]
Dear MGnify team,

I had the following error when I try running virify.sh on an example fasta file

> ValidationException: The CWL reference runner no longer supports pre CWL v1.0 documents. Supported versions are: 
> v1.0
> v1.1
> v1.1.0-dev1 (with --enable-dev flag only)
> v1.2.0-dev1 (with --enable-dev flag only)
> v1.2.0-dev2 (with --enable-dev flag only)

I have tried upgrading the toil and cwltool packages to their latest versions and also installed two packages required as a result of these updates, I then get the following error:

> schema_salad.exceptions.ValidationException: src/pipeline.cwl:12:1: union[str, int, schema_salad.avro.schema.Schema, list, list, dict, list,
>                        None] object expected; got ruamel.yaml.scalarfloat.ScalarFloat
> (emgvp) uludagm@kw60408:~/biosphere/emg-viral-pipeline/cwl$ find . -name \*.cwl

--mahmut

**Comment by mberacochea** [comment]
Hey Mahmut, thank you for reporting this. I'll fix this as soon as I can.

**Comment by uludag** [comment]
Thanks Martin,  I have also tried running an example with nextflow with/without docker options. I had errors in both cases. This is the first time I'm running nextflow, I will try again later and report in a new issue if I think the errors need to be reported
--mahmut

**Comment by hoelzer** [comment]
> 
> 
> Thanks Martin, I have also tried running an example with nextflow with/without docker options. I had errors in both cases. This is the first time I'm running nextflow, I will try again later and report in a new issue if I think the errors need to be reported
> --mahmut

Hi @uludag yes, if you experience issues w/ the Nextflow version as well please feel free to open an issue! Thanks!

**Comment by uludag** [comment]
Thanks @hoelzer, I opened an issue, #50, to share the error I see when running the pipeline with Nextflow.

**Comment by mberacochea** [comment]
All the cwl files are using stable version of the .cwl spec. I'm closing this now, please let us know if you bump into issues with toil / cwltool and the cwl version of the pipeline.
