### ISSUE TITLE
GFF generation for the integration with mgnify

### ISSUE THREAD

**Issue by mberacochea** [EBI-Metagenomics/emg-viral-pipeline#5]

**Comment by hoelzer** [comment]
Is this still valid and needed @mberacochea ? I think back then we discussed this feature to basically show annotated ORFs in a contig browser? For me, this still sounds like a good feature to provide a final GFF-styled output for all contigs and their ORF annotations.

**Comment by mberacochea** [comment]
I need to improve my github notifications filter on my email :facepalm: . 
Yes, having the results as a gff is something we should provide.. I've had some requests for this already.
I'm closing this in favour of a new feature ticket.
