### ISSUE TITLE
There are no stable releases

### ISSUE THREAD

**Issue by samfux84** [EBI-Metagenomics/emg-viral-pipeline#70]
Hi,

The README.md file states:

"We highly recommend to run stable releases, also for reproducibility"

But when I check 

https://github.com/EBI-Metagenomics/emg-viral-pipeline/releases

then I can only find 4 pre-releases, but no stable release. This is a bit confusing.

Best regards

Sam

**Comment by hoelzer** [comment]
Hey @samfux84 thanks for the hint! And yes, you're right. We were a bit too optimistic when writing the README and now the first non pre-release is lacking a bit behind ;) Hopefully, we can have that soon.
