### ISSUE TITLE
Spades version 1.3.4 unavailable in docker hub (-r v0.4.0)

### ISSUE THREAD

**Issue by felipeborim789** [EBI-Metagenomics/emg-viral-pipeline#71]
When using option "--illumina", the pipeline tries to pull spades version v3.14 (microbiomeinformatics/spades:v3.14),
however, only version 3.15.3 is available in the docker hub (microbiomeinformatics/spades:3.15.3)

**Comment by mberacochea** [comment]
Hi @felipeborim789 , thank you for reporting the issue. I'll restore the container for spaces:v3.14, it was deleted by accident.

**Comment by hoelzer** [comment]
thx @mberacochea ! We could in that context also update the SPAdes version used in the pipeline... using v3.15.5

@felipeborim789 but you might also consider just generating the assembly yourself beforehand and then directly use the FASTA file with the contigs as input to the pipeline. A basic assembly option is part of the nextflow pipeline but we mainly maintain the part after the assembly (so the actual virus classification).

**Comment by mberacochea** [comment]
Definitly, we need to upgrade Spades ([Issue](https://github.com/EBI-Metagenomics/emg-viral-pipeline/issues/74)). 
On the meatime, I just restored the container that was missing (https://hub.docker.com/layers/microbiomeinformatics/spades/v3.14/images/sha256-6f7a3a9482ac6bf83058b3307c085767e3140cfb5545b623df18184f7e5727b7?context=repo)

I'm closing this ticket, please re-open it @felipeborim789 if you bump into any issues with spades.
