### ISSUE TITLE
Availability of species specific HMMs

### ISSUE THREAD

**Issue by rickbeeloo** [EBI-Metagenomics/emg-viral-pipeline#72]
Hey :)

We would love to use the VIRify species-specific HMMs to analyze our collections of contigs. We saw the scripts [here](https://github.com/EBI-Metagenomics/emg-viral-pipeline/tree/master/bin/models_vs_uniprot_check) to subset these from the complete ViPhogs. Since you already generated these files, could you provide the `ViPhOG_viral_specific_df.pkl` file on the GitHub? or a tabular format of the species-specific HMMs.

Thanks in advance!

**Comment by hoelzer** [comment]
Hey @rickbeeloo thanks for your interest in the pipeline! Let me check, I think that should be possible!

Cheers

**Comment by hoelzer** [comment]
Thanks @guille0387 ! I also put that file in the OSF repo https://osf.io/fbrxy/

**Comment by rickbeeloo** [comment]
Awesome, thanks!
