### ISSUE TITLE
Add Tower execution feature to README

### ISSUE THREAD

**Issue by hoelzer** [EBI-Metagenomics/emg-viral-pipeline#83]
It's quite simple to monitor a pipeline run via tower.nf:

![image](https://user-images.githubusercontent.com/14393703/210227623-a46f37a9-2df6-40a2-b58d-983cda96367a.png)

We could add a section to the README, e.g., after the `## Profiles` section in the already updated README in the dev branch (github is converting some of the md below automatically, should work to just copy from raw mode):

```md
## Monitoring

<img align="right" width="400px" src="figures/tower.png" alt="Monitoring with Nextflow Tower" /> 

To monitor your Nextflow computations, VIRify can be connected to [Nextflow Tower](https://tower.nf). You need a user access token to connect your Tower account with the pipeline. Simply [generate a login](https://tower.nf/login) using your email and then click the link sent to this address.

Once logged in, click on your avatar in the top right corner and select "Your tokens." Generate a token or copy the default one and set the following environment variable:

```bash
export TOWER_ACCESS_TOKEN=<YOUR_COPIED_TOKEN>
```

You can save this variable in your `.bashrc` or `.profile` to not need to enter it again. Refresh your terminal.

Now run:

```bash
nextflow run EBI-Metagenomics/emg-viral-pipeline -r v0.4.0 --fasta "/home/$USER/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline/nextflow/test/assembly.fasta" --cores 4 -profile local,docker -with-tower
```

Alternatively, you can also pull the code from this repository and activate the Tower connection within the `nextflow.config` file located in the root GitHub directory:

```java
tower {
    accessToken = ''
    enabled = true
} 
```

You can also directly enter your access token here instead of generating the above-mentioned environment variable.
```

**Comment by mberacochea** [comment]
Done in https://github.com/EBI-Metagenomics/emg-viral-pipeline/commit/3c840933463
