### ISSUE TITLE
Fail to run example execution

### ISSUE THREAD

**Issue by ChongLC** [EBI-Metagenomics/emg-viral-pipeline#91]
Dear developer, 

I installed virify via singularity but I failed to run the example execution with the command below: 
```
./nextflow run EBI-Metagenomics/emg-viral-pipeline -r v0.4.0 --fasta "/home/$USER/.nextflow/assets/EBI-Metagenomics/emg-vira                                                                                                                    l-pipeline/nextflow/test/assembly.fasta" --cores 4 -profile local,singularity
```
* Note: I just change the -profile local, docker to -profile local, singularity

Error message:
```
N E X T F L O W  ~  version 22.10.6
Launching `https://github.com/EBI-Metagenomics/emg-viral-pipeline` [distraught_c                                                                                                                    uvier] DSL2 - revision: f367002f0e [v0.4.0]

Profile: local,singularity

Current User: chong
Nextflow-version: 22.10.6
Starting time: 23-01-2023 23:20 UTC
Workdir location:
  /home/chong/primal/work
Databases location:
  nextflow-autodownload-databases

Dev ViPhOG database: v3
Dev Meta database: v2

Only run annotation: false

executor >  local (11)
[e4/6fad74] process > download_pprmeta:pprmetaGet          [100%] 1 of 1 ✔
[23/ee582f] process > download_virsorter_db:virsorterGetDB [  0%] 0 of 1
[7e/2dc2ed] process > download_virfinder_db:virfinderGetDB [100%] 1 of 1 ✔
[09/8fb736] process > download_model_meta:metaGetDB        [100%] 1 of 1 ✔
[60/dfb92e] process > download_viphog_db:viphogGetDB       [  0%] 0 of 1
[7d/06e34c] process > download_ncbi_db:ncbiGetDB           [100%] 1 of 1 ✔
[b9/32d3d7] process > download_checkv_db:checkvGetDB       [  0%] 0 of 1
[19/d88800] process > preprocess:rename (1)                [100%] 1 of 1 ✔
[66/41ecc6] process > preprocess:length_filtering (1)      [100%] 1 of 1 ✔
[-        ] process > detect:virsorter                     -
[a8/c43d73] process > detect:virfinder (1)                 [100%] 1 of 1 ✔
[2c/1d1535] process > detect:pprmeta (1)                   [  0%] 0 of 1
executor >  local (11)
[e4/6fad74] process > download_pprmeta:pprmetaGet          [100%] 1 of 1 ✔
[-        ] process > download_virsorter_db:virsorterGetDB -
[7e/2dc2ed] process > download_virfinder_db:virfinderGetDB [100%] 1 of 1 ✔
[09/8fb736] process > download_model_meta:metaGetDB        [100%] 1 of 1 ✔
[-        ] process > download_viphog_db:viphogGetDB       -
[7d/06e34c] process > download_ncbi_db:ncbiGetDB           [100%] 1 of 1 ✔
[-        ] process > download_checkv_db:checkvGetDB       -
[19/d88800] process > preprocess:rename (1)                [100%] 1 of 1 ✔
[66/41ecc6] process > preprocess:length_filtering (1)      [100%] 1 of 1 ✔
[-        ] process > detect:virsorter                     -
[a8/c43d73] process > detect:virfinder (1)                 [100%] 1 of 1 ✔
[2c/1d1535] process > detect:pprmeta (1)                   [100%] 1 of 1, failed: 1 ✘
[-        ] process > detect:parse                         -
[-        ] process > postprocess:restore                  -
[-        ] process > annotate:prodigal                    -
[-        ] process > annotate:hmmscan_viphogs             -
[-        ] process > annotate:hmm_postprocessing          -
[-        ] process > annotate:ratio_evalue                -
[-        ] process > annotate:annotation                  -
[-        ] process > annotate:plot_contig_map             -
[-        ] process > annotate:assign                      -
[-        ] process > annotate:checkV                      -
[-        ] process > plot:generate_krona_table            -
[-        ] process > plot:krona                           -
[-        ] process > plot:generate_sankey_table           -
[-        ] process > plot:sankey                          -
Error executing process > 'detect:pprmeta (1)'

Caused by:
  Process `detect:pprmeta (1)` terminated with an error exit status (255)

Command executed:

  [ -d "pprmeta" ] && cp pprmeta/* .
  ./PPR_Meta assembly_renamed_filt1500bp.fasta assembly_pprmeta.csv

Command exit status:
  255

Command output:

  Using TensorFlow backend.
  Illegal instruction (core dumped)
  python predict.py model_a.h5: Illegal instruction

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  WARNING: underlay of /etc/localtime required more than 50 (94) bind mounts

  Using TensorFlow backend.
  Illegal instruction (core dumped)
  python predict.py model_a.h5: Illegal instruction
  Error using dlmread (line 62)
  The file 'tmp/predict.csv' could not be opened because: No such file or directory

  Error in PPR (line 96)


  Error in PPR_Meta (line 49)

  MATLAB:dlmread:FileNotOpened
  INFO:    Cleaning up image...

Work dir:
  /home/chong/primal/work/2c/1d153586b94115460798aa673604d2

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

I noticed that there is no tmp folder, which showcased this error: `The file 'tmp/predict.csv' could not be opened because: No such file or directory`

Do you have any suggestions to tackle this issue? 

Best regards, 
Chong

**Comment by hoelzer** [comment]
Hey @ChongLC , thanks for using the pipeline. 

Something seems wrong with PPR-Meta. 

Did you look for the `tmp` folder in here `/home/chong/primal/work/2c/1d153586b94115460798aa673604d2` ?

In this folder, you should also finde a `.command.log` that might have more information. 

For troubleshooting, it would be interesting to see if the tool and the singularity container work on your system. The pipeline should have downloaded the singularity image to a folder `singularity`. And the code base to a `nextflow-autodownload-databases` folder. You can use the singularity image via

`singularity exec <image-path>` 

And then navigate to the pprmeta folder in the database folder and try

`./PPR_Meta --help`

I can't test it ATM, so the commands might be slightly different.

Maybe it also helps to remove the pprmeta singularity image and let the pipeline pull it again. 

However, I am afraid there is something else clashing with your system configuration but it's hard to tell.

Could you also try Docker?

**Comment by ChongLC** [comment]
Dear developer, 

Yes, I checked from the `tmp` folder in `/home/chong/primal/work/2c/1d153586b94115460798aa673604d2`. There is only `file1.fna`.

I have checked the `.command.log`. Below is the message in the command log file: 
```
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (94) bind mounts
 
Using TensorFlow backend.
Illegal instruction (core dumped)
python /home/chong/primal/work/2c/1d153586b94115460798aa673604d2/predict.py /home/chong/primal/work/2c/1d153586b94115460798aa673604d2/model_a.h5: Illegal instruction
Error using dlmread (line 62)
The file '/home/chong/primal/work/2c/1d153586b94115460798aa673604d2/tmp/predict.csv' could not be opened because: No such file or directory

Error in PPR (line 96)


Error in PPR_Meta (line 49)

MATLAB:dlmread:FileNotOpened
INFO:    Cleaning up image...
```

**Comment by ChongLC** [comment]
Dear @hoelzer, 

It is a bit hard for me to use docker on this shared machine. So, it will be great if I can find out a solution for the singularity approach. 

Looking forward to hearing from you. Thank you. 

Best regards, 
Chong

**Comment by hoelzer** [comment]
Hey @ChongLC , okay I think then you should first try if you get PPR-Meta running in general on your system. 

See:
https://github.com/zhenchengfang/PPR-Meta

Here you can also see some details how colleagues installed all the necessary dependencies for PPR-Meta in a Docker container:
https://github.com/replikation/What_the_Phage/blob/master/phage-tool-Dockerfiles/PPR-Meta/Dockerfile

You could use that to set-up an Conda environment, I think, and then try if PPR-Meta works for you or if any system dependencies are missing. If so, we might be able to also add them to the container and then you can use the pipeline.

**Comment by ChongLC** [comment]
Hi @hoelzer, 

Thank you for the reply. Interestingly, I tried to install virify on another shared machine. It works perfectly and tried the first run with my own dataset. 

I am not sure if should I just close this issue. I may need some time to check on the installation issue in the first machine. Please feel free to close this issue if necessary. 

Best regards, 
Chong

**Comment by hoelzer** [comment]
Hey @ChongLC great! Okay, I think there is some issue with the machine configuration where VIRify failed. As it will be challenging to investigate, I will close the issue. But please feel free to report/reopen if you discover anything to share.
