### ISSUE TITLE
Missing CheckV output when there are multiple prophages in contig

### ISSUE THREAD

**Issue by Ales-ibt** [EBI-Metagenomics/emg-viral-pipeline#92]
Hello there!

I'm running Virify through Nextflow and realized the CheckV directory is missing when more than one prophage is predicted in the same contig. Tracing back the log files, I found the error:

`Please remove duplicated sequence IDs from the input FASTA file: XXX: cannot stat 'prophages/quality_summary.tsv': No such file or directory
`

Adding the coordinates to the sequence IDs in the provirus fasta file would solve the problem.

Bests!

**Comment by mberacochea** [comment]
Perfect, thank you Ale. I'll take a look

**Comment by Ales-ibt** [comment]
Me again...

After taking a look at the output files and tracing back the checkV results, I have the following summary of problems associated with the integration of the outputs:

**Problems related to the integration of predicted phages and quality:**
1. CheckV is running on the full contig for prophages 
2. Multiple phages occurring in the same contig are missing
3. Prophages coordinates in the gff don't correspond to coordinates prediction
4. Prophages with no CDS matching ViPhOG are excluded in the gff (is this for quality control?)
5. Viral genomes in full contigs are missing in the gff output

**Problems related to the GFF file format (which is not validated):**
1. Protein IDs in gff file are missing
2. Add the mobile_genetic_element feature and the corresponding coordinates. Then link the corresponding CDS using the 'Parent' key in the attributes field
3. Fix the CDS coordinates in the context of the full contig instead of the subsequence

Find attached some figures I prepared for this report.

Bests,


Alejandra.
[virify_bug_Feb2023.pdf](https://github.com/EBI-Metagenomics/emg-viral-pipeline/files/10804601/virify_bug_Feb2023.pdf)

**Comment by hoelzer** [comment]
Hey @Ales-ibt  - wow, thanks for the detailed report and visuals!

**Comment by mberacochea** [comment]
Fixed by https://github.com/EBI-Metagenomics/emg-viral-pipeline/pull/95 and https://github.com/EBI-Metagenomics/emg-viral-pipeline/pull/94
